apiVersion: sisyphus/v1
kind: Deployment
metadata:
  name: echo
config:
  env: prod
  image: us-docker.pkg.dev/acme/containers/echo_config:latest
  service:
    ports:
      http:  # the name of the port in the Starlark config
        name: http  # optional, allows renaming ports in the service
        number: 80
  variables:
    google-credentials:
      secretKeyRef:
        name: google
        key: google-application-credentials.json
    secret-token:
      secretKeyRef:
        name: tokens
        key: secret-token
footprint:
  gke_acme_us-central1_ap-us-central1:
    replicas: 1
  gke_acme_us-west4_ap-us-west4:
    replicas: 1

---

apiVersion: sisyphus/v1
kind: KubernetesYaml
metadata:
  name: secrets
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: google
    stringData:
      google-application-credentials.json: replace-me
  - apiVersion: v1
    kind: Secret
    metadata:
      name: tokens
    stringData:
      secret-token: replace-me
# alternatively you could import Kubernetes YAML from another file like this:
# sources:
#   - secret.yaml
clusters:
  - gke_acme_us-central1_ap-us-central1
  - gke_acme_us-west4_ap-us-west4

---

apiVersion: sisyphus/v1
kind: CronJob
metadata:
  name: echo-cleanup
config:
  env: prod
  # Not actually defined in //example/echo but it's the same process as the echo server
  image: us-docker.pkg.dev/acme/containers/echo_job_config:latest
  schedule: "0 2 * * *"  # Run daily at 2 AM
footprint:
  gke_acme_us-central1_ap-us-central1: {}
  gke_acme_us-west4_ap-us-west4: {}

---

apiVersion: sisyphus/v1
kind: SisyphusYaml
metadata:
  name: and-even-more-sisyphus-yaml-files
sources:
  - ingress.yaml
