apiVersion: sisyphus/v1
kind: SisyphusDeployment
metadata:
  name: echo
config:
  env: prod
  image: us-docker.pkg.dev/acme/containers/echo_config:latest
  variables:
    google-credentials:
      secretKeyRef:
        name: google
        key: google-application-credentials.json
    secret-token:
      secretKeyRef:
        name: tokens
        key: secret-token
footprint:
  gke_acme_us-central1_ap-us-central1:
    replicas: 1
  gke_acme_us-west4_ap-us-west4:
    replicas: 1

---

apiVersion: sisyphus/v1
kind: KubernetesYaml
metadata:
  name: secrets
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: google
    stringData:
      google-application-credentials.json: replace-me
  - apiVersion: v1
    kind: Secret
    metadata:
      name: tokens
    stringData:
      secret-token: replace-me
clusters:
  - gke_acme_us-central1_ap-us-central1
  - gke_acme_us-west4_ap-us-west4

---

apiVersion: sisyphus/v1
kind: KubernetesYaml
metadata:
  name: you-can-include-kubernetes-yaml-files
sources:
  - service.yaml
clusters:
  - gke_acme_us-central1_ap-us-central1
  - gke_acme_us-west4_ap-us-west4

---

apiVersion: sisyphus/v1
kind: SisyphusYaml
metadata:
  name: and-even-more-sisyphus-yaml-files
sources:
  - ingress.yaml
