apiVersion: v1
kind: Secret
metadata:
  name: google
stringData:
  google-application-credentials.json: replace-me

---

apiVersion: v1
kind: Secret
metadata:
  name: tokens
stringData:
  secret-token: replace-me
